
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.box = "kali-amd64"
  
  config.vm.network "private_network", type: 'dhcp',
    virtualbox__intnet: true

end
