Vagrant.configure("2") do |config|
  config.vm.box = "pfSense"

  # pfSense requires two virtual CPUs to function
  config.vm.provider "vmware_desktop" do |v|
    v.vmx["numvcpus"] = 2
    v.vmx["memsize"] = 2048
  end

  config.vm.network "private_network", type: 'dhcp', vmware_vmx: { intnet: true }
end

