
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.box = "pfSense"

  config.vm.provider "virtualbox" do |v|
    v.cpus = 2
    v.memory = 2048
  end
  
  config.vm.network "private_network", type: 'dhcp',
    virtualbox__intnet: true

end
