Vagrant.configure("2") do |config|
  config.vm.box = "pfSense"

  # pfSense requires two virtual CPUs to function
  config.vm.provider "virtualbox" do |v|
    v.cpus = 2
    v.memory = 2048
  end

  config.vm.network "private_network", type: 'dhcp', virtualbox__intnet: true

end
